title: "@akaoio/ui"
description: "Powerful vanilla JavaScript UI framework with Web Components"
name: "@akaoio/ui"
usage: |
  import { UI, Component } from '@akaoio/ui'
  
  class MyComponent extends Component {
    render() {
      return `<div class="my-component">Hello World</div>`
    }
  }
  
  const ui = new UI()
  ui.register('my-component', MyComponent)
features:
  - "Zero Dependencies - Pure vanilla JavaScript implementation"
  - "Web Components - Custom elements with Shadow DOM support" 
  - "CSS-in-JS - Style definitions as JavaScript modules"
  - "Component System - Modular architecture with lifecycle management"
  - "Theme Support - Built-in light/dark theme switching"
  - "Modern Standards - ES6+ modules and web platform APIs"
